name: Shields data builder

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  update-hash-params:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: dante-signal31/rust-app-version@v1.0.0
      id: hash_params_ver
      with:
        cargo_toml_folder: 'hash_params/'
    - name: Update hash_params version
      uses: jossef/action-set-json-field@v2
      with:
        file: '.custom_shields/hash_params.json'
        field: message
        value: ${{ steps.hash_params_ver.outputs.app_version }}
    - uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: "Update hash params badge data via Github Action"

  update-process-hollowing:

    runs-on: ubuntu-latest
    needs: update-hash-params

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: dante-signal31/rust-app-version@v1.0.0
      id: process_hollowing_ver
      with:
        cargo_toml_folder: 'process_hollowing/'
    - name: Update process_hollowing version
      uses: jossef/action-set-json-field@v2
      with:
        file: '.custom_shields/process_hollowing.json'
        field: message
        value: ${{ steps.process_hollowing_ver.outputs.app_version }}
    - uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: "Update process hollowing badge data via Github Action"

  update-process-migration:

    runs-on: ubuntu-latest
    needs: update-process-hollowing

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: dante-signal31/rust-app-version@v1.0.0
      id: process_migration_ver
      with:
        cargo_toml_folder: 'process_migration/'
    - name: Update process_migration version
      uses: jossef/action-set-json-field@v2
      with:
        file: '.custom_shields/process_migration.json'
        field: message
        value: ${{ steps.process_migration_ver.outputs.app_version }}
    - uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: "Update process migration badge data via Github Action"

  update-remote-access-trojan:

    runs-on: ubuntu-latest
    needs: update-process-migration

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: dante-signal31/rust-app-version@v1.0.0
      id: remote_access_trojan_ver
      with:
        cargo_toml_folder: 'remote_access_trojan/'
    - name: Update remote_access_trojan version
      uses: jossef/action-set-json-field@v2
      with:
        file: '.custom_shields/remote_access_trojan.json'
        field: message
        value: ${{ steps.remote_access_trojan_ver.outputs.app_version }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update remote access trojan badge data via Github Action"

  update-tcp-reverse-shell:

    runs-on: ubuntu-latest
    needs: update-remote-access-trojan

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: dante-signal31/rust-app-version@v1.0.0
      id: tcp_reverse_shell_ver
      with:
        cargo_toml_folder: 'tcp_reverse_shell/'
    - name: Update tcp_reverse_shell version
      uses: jossef/action-set-json-field@v2
      with:
        file: '.custom_shields/tcp_reverse_shell.json'
        field: message
        value: ${{ steps.tcp_reverse_shell_ver.outputs.app_version }}
    - uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: "Update reverse shell badge data via Github Action"

  update-xor-params:

    runs-on: ubuntu-latest
    needs: update-tcp-reverse-shell

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: dante-signal31/rust-app-version@v1.0.0
      id: xor_params_ver
      with:
        cargo_toml_folder: 'xor_params/'
    - name: Update xor_params version
      uses: jossef/action-set-json-field@v2
      with:
        file: '.custom_shields/xor_params.json'
        field: message
        value: ${{ steps.xor_params_ver.outputs.app_version }}
    - uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        commit_message: "Update xor params badge data via Github Action"
